/**
 * @author Themba Malungani <themba.clarence@gmail.com>
 * @description This processes lead service requests
 * @date 2019-09-06
 */
public class LeadServiceCreateHandler extends BaseHttpMethodHandler {

    /**
     * LeadServiceCreateHandler default constructor
     */
    public LeadServiceCreateHandler() {}

    /**
     * Handles the http request by delegating the handling to the instance of IHttpMethodHandler
     * passed
     *
     * @param HttpHandler.Request request
     * @return HttpHandler.Response
     */
    public override HttpHandler.Response handle(HttpHandler.Request request) {

        return null;
    }
}
