/**
 * @author Themba Malungani <themba.clarence@gmail.com>
 * @description This is the http response class
 * @date 2019-09-07
 */
public class HttpResponse {

    /**
     * HttpResponse default constructor
     */
    public HttpResponse() {}

    /**
     * Check if the requests was successful or not
     *
     * @return Boolean
     */
    public Boolean isSucces() {

        return true;
    }
}
