/**
 * @author Themba Malungani <themba.clarence@gmail.com>
 * @description This is the http request class
 * @date 2019-09-07
 */
public class HttpRequest {

    /**
     * HttpRequest default constructor
     */
    public HttpRequest() {}

    /**
     * Creates a HttpRequest from RestRequest
     *
     * @param RestRequest request
     * @return HttpRequest
     */
    public static HttpRequest fromContext(RestRequest request) {

        return null;
    }
}
